### ISSUE TITLE
Sukurti testinių duomenų paketą

### ISSUE THREAD

**Issue by malas** [erikasaves/rdfn#14]
Testiniai duomenys turi inscenizuoti realius duomenis, kad būtų galima neturint duomenų sukūrimo per web appsą galimybės susikurti reikiamus servisus jų išvedimui.

**Comment by erikasaves** [comment]
PERSONAL INFO
Full name: Erikas Mališauskas
Tagline: Passionate UI/UX designer
Location: Vilnius, Lithuania
Phone: +370 (629) 26 815
Email: erikas@malisauskas.lt

SUMMARY
I have more than 4 years professional experience of Photoshop and more than 3 years experience with HTML/CSS. Also, as the internet goes mobile I'm also working with Bootstrap to make the websites mobile-friendly aswell. In my opinion, the biggest strength of mine is that I am a graphic designer thinking in code.

WORKING EXPERIENCE
Company: Mediapark
Position: Senior designer
Date: October 2011 - May 2014 (2 years 8 months)
Description: Types of graphic design - basically Web design (UI, HTML, CSS), but there were some prints, business cards and banners I designed.
---
Company: MailerLite
Position: Designer
Date: May 2014 - June 2015 (1 year 2 months)
Description: Redesigning MailerLite user interface, working with drag and drop builder and email templates.

EDUCATION
Field of study: Graphic design
School name: Vilnius Academy of Arts
Date: September 2011 - June 2015
Degree name: Bachelor's degree
Description: Learning all types of graphic design - print design, illustrations, web design etc.
---
School name: Vilnius Žirmūnų gymnasium
Date: September 2007 - July 2011
Degree name: High school

CERTIFICATES
Certification name: W3Schools HTML Certificate
Issuing authority: W3Schools
Date: September 2014 - December 2014
Description: Cras justo odio, dapibus ac facilisis in, egestas eget quam.

SKILLS
Name: Photoshop
Skill: 9/10
---
Name: Sketch
Skill: 8/10
---
Name: HTML/CSS
Skill: 9/10
---
Name: Bootstrap
Skill: 8/10

LANGUAGES (tokiu pat principu kaip skills)
Name: Lithuanian 
Skill: 10/10
---
Name: English
Skill: 9/10
---
Name: Russian
Skill: 3/10

**Comment by malas** [comment]
Čia ne tik šiaip data, bet ir programiškai reikia :) Pas mus tame html folderyje yra koks nors CV template pilnai sukurtas?

**Comment by erikasaves** [comment]
Ne, HTML'o kol kas nėra, bet poros dienų bėgy bus :)
